package com.appdynamics.inventory;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OrderServiceImplService", targetNamespace = "http://inventory.appdynamics.com/", wsdlLocation = "http://localhost:8080/cart/orderService?wsdl")
public class OrderServiceImplService
    extends Service
{

    private final static URL ORDERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.appdynamics.inventory.OrderServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.appdynamics.inventory.OrderServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://ws:8080/cart/orderService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://ws:8080/cart/orderService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ORDERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public OrderServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderServiceImplService() {
        super(ORDERSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://inventory.appdynamics.com/", "OrderServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "OrderServiceImplPort")
    public OrderService getOrderServiceImplPort() {
        return super.getPort(new QName("http://inventory.appdynamics.com/", "OrderServiceImplPort"), OrderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "OrderServiceImplPort")
    public OrderService getOrderServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://inventory.appdynamics.com/", "OrderServiceImplPort"), OrderService.class, features);
    }

}
